---
# tasks file for ansible-role-screen-switch

- name: install cec-utils to control screen
  apt:
    name: cec-utils
    state: present

- name: copy screen control script
  copy:
    src: screen_switch.sh
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0755

- name: copy screen switch systemd template
  copy:
    src: screen_switch@.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644

- name: create timers from templates
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - screen_on.timer
    - screen_standby.timer

- name: enable screen control services
  systemd:
    name: "{{ item.unit }}"
    enabled: yes
    state: started
  with_items:
    - unit: screen_on.timer
    - unit: screen_standby.timer
